apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    tier: cluster-addons
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: CLUSTER
    namespace: cert-manager
  project: default
  source:
    repoURL: https://github.com/devOwlish/argocd-demo.git
    path: manifests/cert-manager
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
