apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All app names must be unique across the ArgoCD instance
# So let's prefix the app names with the cluster name (demo-worker2-)
namePrefix: demo-worker2-

resources:
  - ../../base/addons/cert-manager
  - ../../base/addons/ingress-nginx
  - ../../base/addons/reflector

patches:
  # Override .spec.destination.name
  - path: destination.yaml
    target:
      kind: Application
