apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: in-cluster-

resources:
  - ../../base/addons/cert-manager
  - ../../base/addons/ingress-nginx
  - ../../base/addons/reflector

patches:
  # Override .spec.destination.name
  - path: destination.yaml
    target:
      kind: Application
  # App-specific patches
  - path: cert-manager.yaml
    target:
      kind: Application
      name: cert-manager
  - path: reflector.yaml
    target:
      kind: Application
      name: reflector
