apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.14.3
    namespace: cert-manager
    valuesInline:
      fullnameOverride: cert-manager
      installCRDs: true

resources:
  - cluster-issuer.yaml
